#! /usr/bin/env python
import rospy
import actionlib

# import the custom messages generated by the action file
from drone_action_pkg.msg import DroneAction, DroneFeedback, DroneResult

class DroneActionServer(object):
    
  # create messages that are used to publish feedback/result
  _feedback = DroneFeedback()
  _result   = DroneResult()

  def __init__(self):
    # creates the action server
    self._as = actionlib.SimpleActionServer("drone_action_server", DroneAction, self.goal_callback, False)
    self._as.start()
    rospy.loginfo("Drone Action Server is Ready!")
    self.state = "LANDED" # Drone starts in landed state
    
  def goal_callback(self, goal):
    # this callback is called when the action server is called
    command = goal.command
    success = True
    rate = rospy.Rate(1) # 1 Hz for feedback once a second
    
    if command == "TAKEOFF":
        rospy.loginfo("Command received: TAKEOFF")
        if self.state == "TAKEOFF":
            rospy.logwarn("Drone is already in take off position!")
        else:
            # Simulate taking off over a few seconds
            for i in range(4):
                if self._as.is_preempt_requested():
                    rospy.loginfo('The goal has been cancelled/preempted')
                    self._as.set_preempted()
                    success = False
                    break
                self._feedback.current_action = "take off"
                self._as.publish_feedback(self._feedback)
                rate.sleep()
            
            if success:
                self.state = "TAKEOFF"
                rospy.loginfo("Drone has taken off successfully and is waiting in position.")

    elif command == "LAND":
        rospy.loginfo("Command received: LAND")
        if self.state == "LANDED":
            rospy.logwarn("Drone is already landed!")
        else:
            # Simulate landing over a few seconds
            for i in range(4):
                if self._as.is_preempt_requested():
                    rospy.loginfo('The goal has been cancelled/preempted')
                    self._as.set_preempted()
                    success = False
                    break
                self._feedback.current_action = "landing"
                self._as.publish_feedback(self._feedback)
                rate.sleep()
            
            if success:
                self.state = "LANDED"
                rospy.loginfo("Drone has landed successfully.")
    else:
        rospy.logerr("Unknown command. Please send TAKEOFF or LAND.")
        success = False
        
    if success:
        # When the action finishes, the result will return nothing (we set finished=True based on your Drone.action)
        self._result.finished = True
        self._as.set_succeeded(self._result)

if __name__ == '__main__':
  rospy.init_node('drone_action_node')
  server = DroneActionServer()
  rospy.spin()
